### ISSUE TITLE
transport/http/request: Request.Clone() must take a context.

### ISSUE THREAD

**Issue by moriyoshi** [aws/smithy-go#230]
https://github.com/awslabs/smithy-go/blob/6b00191/transport/http/request.go#L39

This doesn't allow one to correctly replicate `net/http` 's `Request.Clone()`.

**Comment by jasdel** [comment]
Thanks for reaching out with this issue @moriyoshi. The `smithyhttp.Request`'s `Clone` intentional did not accept a context via its clone method. The intention behind this was that the `Request`'s `Build` method was the entity that attached the context to the underlying `http.Request` and returned a constructed `http.Request`. Prior to `Build` being called the http.Request would not have a `Context` associated with it. `Build` is intended to be the last action performed on the request before it is used with the HTTP Client.

Could you go into more detail and background about the use case for `Clone` to take a context?

**Comment by moriyoshi** [comment]
So what is the use of Clone() in the first place? Is it supposed to be used only in a middleware? I guess not, because it's used in RequestCloner, whose comment says it's intended to use in a retrier.  Then should the  retrier be able to feed a fresh context on a retry? I would say yes.

**Comment by jasdel** [comment]
Thanks for the update. The intention of the middleware is that a context is only associated with an individual request at the last possible moment. Basically right before the request is passed to the HTTP client's `Do` method.  This is the reason for `Build` taking the context but not `Clone`. Clone is intended to create a copy of the smithyhttp.Request, and that request has no reference to a Context.

The retryer will create a clone of the request to ensure the request body stream is reset correctly.  It doesn't need provide a context, because the request is context-less until Build is called when the request is sent to the HTTP client.

**Comment by jasdel** [comment]
Thanks for reaching out @moriyoshi. I'm going to close this issue. Please reach out and let us know if you have additional questions, feedback, issues, or feature request.
